### ISSUE TITLE
L5 Update to include PSR-4

### ISSUE THREAD

**Issue by scottconnerly** [michaeldyrynda/phpstorm-laravel-code-style#1]
http://laravel.com/docs/5.0/contributions#coding-style
(4.2 was PSR-0)

**Comment by michaeldyrynda** [comment]
Anything specific you'd like changed? PSR-0 and PSR-4 refer to auto loading and namespacing, not code style.

**Comment by scottconnerly** [comment]
True they do. Got me there. Thanks for humoring me!
