### ISSUE TITLE
Config spams errors in phpstorm 8.0.3

### ISSUE THREAD

**Issue by asvae** [michaeldyrynda/phpstorm-laravel-code-style#2]
Check the screenshot: https://www.dropbox.com/s/xf0kop5i2iiqacc/screenshoot_00856.png?dl=0
I managed to fix error, but got another one.

**Comment by michaeldyrynda** [comment]
That's interesting. I've not experienced this issue with the two (OS X) machines with 8.0.3 I've added the code styles to in the last month or two. Perhaps it's a Windows issue? Unfortunately, I don't have a Windows machine to test this on.

**Comment by asvae** [comment]
Meh, I just downloaded html instead of xml. Sorry for bother.
