### ISSUE TITLE
Its okay for 5.2 and 5.3 to? Yes?

### ISSUE THREAD

**Issue by arturmamedov** [michaeldyrynda/phpstorm-laravel-code-style#6]
I think the style code is not changed, you can add it to `README.md`. But  check it out, i not sure.

**Comment by michaeldyrynda** [comment]
It should be, given >= 5.1 just follows PSR2. There are, I'm sure, some minor Laravel-specific formatting choices that aren't explicitly covered, though.

**Comment by arturmamedov** [comment]
Thanks again! :)
