### ISSUE TITLE
What for the `PHPDoc` with 2 spaces after @param  followed by type and more  2 spaces

### ISSUE THREAD

**Issue by arturmamedov** [michaeldyrynda/phpstorm-laravel-code-style#7]
https://laravel.com/docs/5.3/contributions#coding-style

Note that the @param attribute is followed by two spaces, the argument type, two more spaces, and finally the variable name:

``` php
/**
 * Register a binding with the container.
 *
 * @param  string|array  $abstract
 * @param  \Closure|string|null  $concrete
 * @param  bool  $shared
 * @return void
 */
public function bind($abstract, $concrete = null, $shared = false)
{
```

**How we can reproduce this with phpStorm?**

**Comment by michaeldyrynda** [comment]
I don't believe you can. I've asked @grahamcampbell about it in the past and he's said that it's something that StyleCI handles when PRs are merged into the Laravel organisation repositories, but it's something you'd have to do as a custom formatter in PHP CS fixer after the fact for your own code.

**Comment by arturmamedov** [comment]
@michaeldyrynda Thank you very much! Now i'm quite bout this :)
