### ISSUE TITLE
Array aligning

### ISSUE THREAD

**Issue by christophrumpel** [michaeldyrynda/phpstorm-laravel-code-style#9]
Hey,

thx for the style. I noticed that it is using array aligning like:

```php

$x = [
    0    => "zero",
    123  => "one two three",
    25   => "two five"
];
```

As far as I know Laravel does not use it. (don't ask me why because I love it)

**Comment by michaeldyrynda** [comment]
There's probably a few other things that it does in there Laravel doesn't or no longer does. I don't use PhpStorm much anymore, but I'll try and find some time to update it later. It looks like it's still using tabs, for example 😬

This instance should just be a matter of changing `ALIGN_KEY_VALUE_PAIRS` to `false` 👍

**Comment by christophrumpel** [comment]
Ok thx for letting me know.

**Comment by michaeldyrynda** [comment]
Only two months to get to this, but with 2017.1 out and me playing with it, I actually got around to updating the code styles to more closely match Laravel's defaults.

**Comment by christophrumpel** [comment]
Hey @michaeldyrynda , oh nice. Will check it out. Thx!
